plugins {
    id 'java-library'
    id 'maven-publish'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'com.epam' as Publication
            artifactId = 'utils' as Publication
            version = '1.3.5' as Publication

            from components.java
        }
    }
}

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.10'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
}

jar {
    manifest {
        attributes 'Implementation-Title':'StringUtils Utility Library',
                    'Implementation-Version':'1.3.5'
    }
}

test {
    useJUnitPlatform()
}

publishMavenPublicationToMavenLocal {}.mustRunAfter('build')